name: ashuothshh job 
# trigger point 
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"

# creating jobs 
jobs:
  infra-provision-job:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    # calling first github action to clone my dryrun-aws data to runner machine 
    - name: taking code from my repo 
      uses: actions/checkout@v5
      with:
        ref: master 
# terrafor installing 
    - name: installing terraform 
      uses: hashicorp/setup-terraform@v3
# running some commands 
    - name: my first step to test github action 
      run: |
        echo "Hello world"
        git version 
        whoami
        ls -a 
        terraform version
    # configure aws secret keys 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: verify aws connection 
      run: | 
        echo "checking with command"
        aws s3 ls 
    - name: deploy terraform resources 
      run: | 
        echo "implementing terraform deals"
        terraform init 
        terraform plan 
        sleep 2
        terraform apply --auto-approve 

  infra-destroy-job:
    needs: infra-provision-job
    runs-on: ubuntu-latest
    steps:
    - name: checking out code 
      uses: actions/checkout@v5
      with:
        ref: master 
    - name: login to aws creds 
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    # isntalling  
    - name: installing terraform 
      uses: hashicorp/setup-terraform@v3

    - name: destroying it 
      run: | 
        echo "checking resoruces"
        terraform init 
        terraform state list
        terraform destroy --auto-approve


          

  