# name of pipeline workflow
name: Ashutoshh terraform workflow 
# trigger action 
# when there is a push happen in master branch pipeline gonna trigger
on: 
  push:
    branches: [ "master" ]  
    paths-ignore:
      - "README.md"

jobs:
# stage 1 with terraform details 
  infra-build:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    - name: hello world printing 
      run: echo "Hello world"